name: Testing on Ubuntu
run-name: Testing on Ubuntu
on:
  - push
  - pull_request
jobs:
  ubuntu:
    runs-on: ubuntu-18.04
    steps:
      - name: GitHub repository checkout
        uses: actions/checkout@v3
      - name: Run script
        run: ./test_script/script.sh
  
